on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:        
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm

    - run: npm ci

    - name: debug
      run: echo "NPM_TOKEN ${#NPM_TOKEN}"

    - name: Config NPM
      run: npm config set '//registry.npmjs.org/:_authToken' '${NPM_TOKEN}'

    - name: Semantic Release
      run: npm run publish

    - name: Get version
      run: git describe --tags --abbrev=0 >> $GITHUB_STEP_SUMMARY
