# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ga-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16, 17, "" ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#check-latest-version
        node-version: ${{ matrix.node-version }}
        check-latest: true
        cache: 'npm'
    - run: npm ci
    - run: npm test
